### ISSUE TITLE
Timestamp stale issue

### ISSUE THREAD

**Issue by CaptAdric** [lukegb/mcassoc#8]
hey, I've got a timestamp stale error message when going through the minecraft assosiation V: 1.0.1

as far as I can tell I've configured the addon correctly but it seems not to be working, I've contacted my web host and the can't see an issue on their end I was wonding if you could help.

Error message:

There was an error while associating your account.

Additional details: timestamp stale

**Comment by lukegb** [comment]
Thanks for the issue (and the email, sorry for not responding earlier)

I'll look into it ASAP, most likely later today

**Comment by lukegb** [comment]
Sorry for the delay in this - I can't reproduce it. It sounds like your server's clock or timezone is set incorrectly and therefore the timestamp check is failing.

I assume you're using @lol768's implementation of this for xenForo?

**Comment by lol768** [comment]
Pretty sure that's using my add-on, the error matches up anyway: https://github.com/lol768/XenForo-MCASSOC/blob/master/addon-AssociationMc.xml#L184-190

**Comment by CaptAdric** [comment]
yes the clock is showing to be 10 mins out. I'm contacting my webhost and I'll get back to you if the issue remains or is fixed

**Comment by CaptAdric** [comment]
yep that was the issue. its all fixed now. Thanks
